### ISSUE TITLE
Equal PM levels

### ISSUE THREAD

**Issue by TBKRK** [Sensirion/arduino-sps#27]
Hi, I'm testing SPS30 in my room and get almost the same values for each PM fraction (identical for PM2.5, PM4.0 and PM10) in each sample. I think it is statistically impossible. On other sensor (SDS011)  values for each PM are significantly different each other. Take a look at my data:
[sps30.pdf](https://github.com/Sensirion/arduino-sps/files/5742994/sps30.pdf)

**Comment by winkj** [comment]
Hi TBKRK,

Unfortunately, we can only support issues with the library on github. For product support, please contact our product support team via this form: https://www.sensirion.com/en/about-us/contact/. Alternatively, if you bought parts through a distributor, they often have support channels as well.

From a library point of view, your output would be consistent with an experiment where most (or all when rounded to two decimal places) of the pollution is <=2.5μm. Since PM4 includes all particles smaller than 4μm, that will include the ones reported in the PM2.5 signal (likewise for PM10), which will give you the same number for all three signals.

 As such, if you look at a sample from your PDF here:
  PM 1.0: 5.06
  PM 2.5: 5.22
  PM 4.0: 5.22
  PM 10.0: 5.22
That's 5.06 μg/m^3 particles of size 1μm or smaller, 0.16 μg/m^3 (5.22-5.06) of particles between 1-2.5μ, 0.00 μg/m^3 (5.22-5.22) particles between 2.5-4μm, and 0.00 μg/m^3 (5.22-5.22) particles between 4-10μm. 

If you look at the number concentration values, you do indeed see a change between PM2.5 and PM4/10, which shows that there is a little bit of extra particles in the 2.5-10μm range, e.g in your sample number 4:
  NC 0.5: 38.57
  NC 1.0: 43.93
  NC 2.5: 44.0**4**
  NC 4.0: 44.0**4**
  NC 10.0: 44.0**5**

Again, that's just an explanation of the library output. Regarding question on the values themselves, please contact our product support team!
